### ISSUE TITLE
What with backward compatibility?

### ISSUE THREAD

**Issue by sszenbit** [giltayar/proposal-types-as-comments#97] opened 2022-03-13 09:07 UTC
So, how this proposal cares about old browsers, or it do not? As I understand, this proposal valid for "new" browsers and node.js, where no need for strict backward compatibility

**Comment by acutmore** [comment] 2022-03-13 09:59
Hi @sszenbit this looks like a duplicate of #76

**Comment by benjamingr** [comment] 2022-03-13 11:03
Yes, going to close as a duplicate. Thanks for your concern.

**Closed by benjamingr** 2022-03-13 11:03 UTC
