### ISSUE TITLE
How do you know which type checker a .js file is written for?

### ISSUE THREAD

**Issue by jamiebuilds** [giltayar/proposal-types-as-comments#46] opened 2022-03-09 20:13 UTC
Given that there are no semantics enforced by this proposal. When a type checker comes across a `.js` file with types-as-comments syntax. How would it know if that file was meant to have that type checker's semantics?

For example, given this this Flow code (imagining it as a `.js` file with types-as-comments):

```ts
function fn(param: bool) {} // "bool" and "boolean" are synonyms in Flow
```

How should TypeScript know that `bool` is not an undeclared type name. It's still valid syntax, and even if it weren't, what kind of UX would TypeScript give here?

This could even happen across versions of a single type checker. Both Flow and TypeScript have made changes in the past that mean old code will produce new errors (I'll give you that it happens more infrequently nowadays).

Today, TypeScript has less of an issue with that because most of your third party types come from `.d.ts` files (which are typescript specific "type definition" files), which are more limited in scope and therefore less likely to have semantic breaking changes.

I'm concerned that there will eventually be so many `.js` files that were written with different versions of different type checkers that the user experience of running a future version of TypeScript (or whatever) against them will lead to a lot of unexpected and confusing errors.

**Comment by acutmore** [comment] 2022-03-09 20:22
The way flow does this for `.js` files right now is you can put a `// @flow` at the top of the file.

https://flow.org/en/docs/usage/#toc-prepare-your-code-for-flow

**Comment by samwgoldman** [comment] 2022-03-09 20:23
Thanks for opening this issue, Jamie! I raised a similar concern earlier and promised to write it up here. :)

The proposal outlines what browser engines are supposed to do with type (ignore them) but this is definitely only half of the story. We would not want to put types into JavaScript files unless _something_ is going to care about them. For tools like TypeScript, Flow, and others, which actually will look at the types, the spec is currently too ambiguous IMO.

**Comment by lhorie** [comment] 2022-03-09 20:27
@acutmore [Hegel](https://hegel.js.org/docs/install) does not provide any obvious way of identifying itself (i.e. it's possible to use it in a zero-config fashion)

**Comment by samwgoldman** [comment] 2022-03-09 20:31
Maybe we should merge with #36?

**Comment by giltayar** [comment] 2022-03-09 22:13
Closing as duplicate of #36.

**Closed by giltayar** 2022-03-09 22:13 UTC
